// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xksrscyjywtnmtwmgihm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhrc3JzY3lqeXd0bm10d21naWhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NzcyMjYsImV4cCI6MjA2NzQ1MzIyNn0.yX65KXWNzewok7zd-V2gNQW97yDryang9jdCdM1-Btg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});